- id: flutter-analyze
  name: Flutter Analyze
  language: system
  always_run: true
  pass_filenames: false
  entry: flutter-analyze

- id: flutter-format
  name: Flutter Format
  language: system
  files: \.dart$
  entry: flutter-format

- id: flutter-import-sort
  name: Flutter Import Sort
  language: system
  files: \.dart$
  entry: flutter-import-sort
