- id: flutter-analyze
  name: Flutter Analyze
  language: dart
  types: [dart]
  entry: flutter analyze --no-fatal-infos --no-fatal-warnings

- id: flutter-format
  name: Flutter Format
  language: dart
  types: [dart]
  entry: flutter format -l 120

- id: flutter-import-sort
  name: Flutter Import Sort
  language: dart
  types: [dart]
  entry: flutter pub run import_sorter:main --no-comments
