- id: flutter-analyze
  name: Flutter Analyze
  language: system
  always_run: true
  pass_filenames: false
  entry: flutter analyze --no-fatal-infos --no-fatal-warnings

- id: flutter-format
  name: Flutter Format
  language: system
  files: \.dart$
  entry: flutter format -l 120

- id: flutter-import-sort
  name: Flutter Import Sort
  language: system
  files: \.dart$
  entry: flutter pub run import_sorter:main --no-comments
